### ISSUE TITLE
Cannot find module '/dist/prerender'

### ISSUE THREAD

**Issue by azz0r** [graphcool/react-router-static-webpack-plugin#1]
```js
Unhandled rejection Error: Cannot find module '/dist/prerender'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Compiler.<anonymous> (/node_modules/react-router-static-webpack-plugin/src/index.js:109:18)
    at Compiler.next (/node_modules/tapable/lib/Tapable.js:69:14)
    at callback (/node_modules/copy-webpack-plugin/dist/index.js:71:17)
    at Object.finallyHandler (/node_modules/bluebird/js/main/finally.js:39:23)
    at Object.tryCatcher (/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by schickling** [comment]
Hey @azz0r. We turned this project into a new one: https://github.com/graphcool/prep
